Fixed polarity of conditional logic in sparrow db import command

diff --git a/_cli/bin/sparrow-db-import b/_cli/bin/sparrow-db-import
--- a/_cli/bin/sparrow-db-import
+++ b/_cli/bin/sparrow-db-import
@@ -5,16 +5,25 @@
 && >&2 echo "File "$1" not found" \
 && exit 1
 
-internal_name="/tmp/database-backup.pg-dump"
-
 # Bring up the database if it isn't running
 sparrow compose exec db echo 'Running' > /dev/null
-isup_db=$?
-if [ $isup_db -eq 0 ]; then
-  echo "Database isn't running, starting it up..."
+isdown_db=$?
+if [ $isdown_db -ne 0 ]; then
+  >&2 echo "Database isn't running, starting it up..."
   sparrow compose up -d db
 fi
 
+# Shut down backend if it's up
+sparrow compose exec backend echo 'Running' > /dev/null
+isdown_backend=$?
+if [ $isdown_backend -eq 0 ]; then
+  >&2 echo "Backend is running, shutting down..."
+  sparrow compose stop backend
+fi
+
+
+internal_name="/tmp/database-backup.pg-dump"
+# Remove the temporary database
 sparrow compose exec -T db bash -s <<EOF
 mkdir -p /tmp
 rm -f "$internal_name"
@@ -22,6 +31,10 @@ EOF
 
 
 container_id=$(sparrow compose ps -q db)
+if [ -z "$container_id" ]; then
+  >&2 echo "Database container not found"
+  exit 1
+fi
 
 docker exec -i $container_id sh -c "cat > $internal_name" < "$1"
 
@@ -39,14 +52,6 @@ fi
 
 sparrow db await
 
-# Shut down backend if it's up
-sparrow compose exec backend echo 'Running' > /dev/null
-isup_backend=$?
-if [ $isup_backend -ne 0 ]; then
-  echo "Backend is running, shutting down..."
-  sparrow compose stop backend
-fi
-
 # Actually run database migration
 sparrow compose exec -T db bash -s <<EOF
 dropdb --if-exists -Upostgres sparrow
@@ -55,12 +60,12 @@ pg_restore -v -Upostgres -d sparrow "$internal_name"
 rm -f "$internal_name"
 EOF
 
-if [ $isup_db -eq 0 ]; then
-  echo "Stopping database"
+if [ $isdown_db -ne 0 ]; then
+  >&2 echo "Stopping database"
   sparrow compose stop db
 fi
 
-if [ $isup_backend -ne 0 ]; then
-  echo "Restarting backend"
+if [ $isdown_backend -eq 0 ]; then
+  >&2 echo "Restarting backend"
   sparrow compose stop db
 fi
