Major reorganization to separate frontend and backend
Local development works but not Dockerized development yet

diff --git a/bin/develop b/bin/develop
--- a/bin/develop
+++ b/bin/develop
@@ -2,7 +2,23 @@
 
 rootDir=${0:h:h}
 
-cd "$rootDir"
+cd "$rootdir"
+
+if [ ! -f backend/setup.py ]; then
+  echo "This must be run within the LABDATA code directory"
+  exit 1
+fi
+
+# If labdata is not installed, install it
+if ! labdata >/dev/null 2>&1; then
+  echo "$(tput bold)labdata$(tput sgr0) command is not found"
+  pip install -e backend
+  pip install -e deps/sadisplay
+  pip install -e import-pipelines/WiscAr-MAP
+fi
+
+cd "$rootDir/frontend"
+npm install
 
 labdata serve &
 $(npm bin)/webpack --watch --mode=development &
