Better sparrow up that bails out when containers fail to build

diff --git a/bin/sparrow-up b/bin/sparrow-up
--- a/bin/sparrow-up
+++ b/bin/sparrow-up
@@ -9,4 +9,12 @@ fi
 
 sparrow compose up --build -d $@
 # Follow logs for running container(s)
-sparrow compose logs -f $@
+exit_code=$?
+if (( $exit_code == 0 )); then
+  echo "$(tput bold)Containers built successfully! Following logs.$(tput sgr0)"
+  sparrow compose logs -f $@
+else
+  echo "$(tput bold)One or more containers did not build properly, aborting.$(tput sgr0)"
+  # Forward exit code to workers
+  exit $exit_code
+fi
